CREATE ROLE admin_interview_scheduler WITH
  LOGIN
  SUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:gAqpa2+9A4w/JCp9sl1Xbw==$/5/2lGDD17fCm8RDtKuSqQTwGzQLm3WFqJbkRCW3tXc=:yOcJM2wm4pLWPSr0p0q/HhIIJypVccvJ9HjL8ZWgiv4=';